### PR TITLE
Waiting for public-key endpoint on son-gtkusr before starting tests

### PR DESCRIPTION
**Pull request by alfonsoegio**

### CODE REVIEW

**Comment by jbonnet** [comment]
Hy, @alfonsoegio 
Please have in mind that the `son-gtkusr` should be invisible from the outside. What you should expect is the `/api/v2/users/public-key` endpoint exposed in the `son-gtkapi`. Integration tests should include the `son-gtkapi`, not the `son-gtkusr`, which will get tested in the end-to-end process. By the way, you already have that in the `/api/v2/micro-services/public-key` endpoint, though in error: I've suggested the `son-gtkusr` to return the public key in a `JSON` object, instead of in pain text.

**Comment by alfonsoegio** [comment]
local check using VPN:
-------------------------------------------------------------------------
$ bash int-gtkusr-keycloak/deployment.sh && bash int-gtkusr-keycloak/tests.sh 
Stopping and removing containers
son-gtkusr
son-gtkusr
son-keycloak
son-keycloak
Building new containers
Creating son-keycloak
Creating son-gtkusr
Waiting for son-gtkusr ...
son-gtkusr Ready!
Waiting for son-gtkusr-keycloak ...
son-keycloak Ready!
Waiting for son-gtkusr public-key ...
son-gtkusr is able to return public-key!
Starting Tests
Success: User Management found
Success: Keycloak found
-------------------------------------------------------------------------

**Comment by alfonsoegio** [comment]
ok, thanks for the warning, tomorrow we'll discuss together with Dani Guija the best way to set up the integration tests regarding both modules

**Comment by dang03** [comment]
Hi @jbonnet,
This integration test, `int-gtkusr-keycloak`, is only and exclusively for `son-gtkusr` and `keycloak` in order to test the `son-gtkusr` (Adapter) API and features with Keycloak, as `son-gtkusr` can't work alone.
The test you are referring to is called `int-usr-management`, which indeed will include `son-gtkapi` and `BSS`, and other components, to test end-to-end processes. However it is not finished yet because we first need to have `son-gtkusr` and `keycloak` working properly.

**Pull request merged**
